OCM-4876 | feat: Add ability to directly edit app-interface with a single flag + tests
openshift-online/ocm-csv-parser pull request #7
Opened 2024-01-11 19:43 UTC by hunterkepley

Introduces the `--app-interface` flag + full flow tests for this

User can supply the root dir (even relatively) for app-interface when parsing a CSV, and the CLI will update and replace the old configmap for that resource with the new one

2024-01-11 19:54 UTC, hunterkepley commented
unit tests pass including new "fullcycle" test for app interface flag

2024-01-12 16:32 UTC, ciaranRoche approved these changes

2024-01-14 20:38 UTC, ziccardi requested changes
Ensure that the `defer file.Close()` is promptly invoked once the file is successfully opened. Neglecting this step may lead to the file never being closed in case an error occurs in the code preceding the defer statement.

2024-01-14 20:38 UTC, ziccardi commented on pkg/convert/convert.go
> +		if appInterfaceDir[len(appInterfaceDir)-1] == '/' {
I think we could use strings.HasSuffix here
```suggestion
		if strings.HasSuffix(appInterfaceDir, "/") {
```

2024-01-14 20:38 UTC, ziccardi commented on pkg/convert/convert.go
> +				finalText += fmt.Sprintf("%s", newConfigmap)
I think this could be replaced with 
```suggestion
				finalText += fmt.Sprintf("%s\n%s", text, newConfigmap)
```

2024-01-14 20:38 UTC, ziccardi commented on pkg/convert/convert.go
> +		defer newFile.Close()
If an error occurs writing the file, the defer is never called and the `newFile.Close()` will never happen.
I think the `defer` should be moved few lines above:
```suggestion
		newFile, err := os.OpenFile(appInterfaceConfigmapFile, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0600)
		if err != nil {
			return err
		}
		defer newFile.Close()

		_, err = newFile.Write([]byte(finalText))
		if err != nil {
			return err
		}
```

2024-01-14 20:38 UTC, ziccardi commented on pkg/convert/convert.go
> +		defer file.Close()
This should be moved close to where the file has been opened.

2024-01-15 14:07 UTC, merged